//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lunar_calendar.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lunar_calendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;LifeWeight&gt;
        ///&lt;item&gt;
        ///&lt;name&gt;tblWeight&lt;/name&gt;
        ///&lt;rowsdata&gt;
        ///
        ///&lt;/rowsdata&gt;
        ///&lt;/item&gt;
        ///
        ///61	XX01YY01	1.2
        ///62	XX02YY02	0.9
        ///63	XX03YY03	0.6
        ///64	XX04YY04	0.7
        ///65	XX05YY05	1.2
        ///66	XX06YY06	0.5
        ///67	XX07YY07	0.9
        ///68	XX08YY08	0.8
        ///69	XX09YY09	0.7
        ///70	XX10YY10	0.8
        ///71	XX01YY11	1.5
        ///72	XX02YY12	0.9
        ///73	XX03YY01	1.6
        ///74	XX04YY02	0.8
        ///75	XX05YY03	0.8
        ///76	XX06YY04	1.9
        ///77	XX07YY05	1.2
        ///78	XX08YY06	0.6
        ///79	XX09YY07	0.8
        ///80	XX10YY08	0.7
        ///81	XX01YY09	0.5
        ///82	XX02YY10	1.5
        ///83	XX03YY11	0. [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string LifeWeight {
            get {
                return ResourceManager.GetString("LifeWeight", resourceCulture);
            }
        }
    }
}
