//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lunar_calendar.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lunar_calendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FileName Name=&quot;24solarterms.xml&quot;&gt;
        ///  &lt;DataTable TableName=&quot;solarterms&quot;&gt;
        ///    &lt;DataColumns&gt;
        ///      &lt;DataColumn ColumnName=&quot;ID&quot; DataType=&quot;System.Int64&quot; Caption=&quot;ID&quot; /&gt;
        ///      &lt;DataColumn ColumnName=&quot;Year&quot; DataType=&quot;System.Int16&quot; Caption=&quot;Year&quot; /&gt;
        ///      &lt;DataColumn ColumnName=&quot;SolarID&quot; DataType=&quot;System.String&quot; Caption=&quot;SolarID&quot; /&gt;
        ///      &lt;DataColumn ColumnName=&quot;SolarName&quot; DataType=&quot;System.String&quot; Caption=&quot;SolarName&quot; /&gt;
        ///      &lt;DataColumn ColumnName=&quot;SolarDate&quot; DataType [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string _24solarterms {
            get {
                return ResourceManager.GetString("_24solarterms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FileName Name=&quot;IDName.xml&quot;&gt;
        ///	&lt;DataTable TableName=&quot;tblIDName&quot;&gt;
        ///		&lt;DataColumns&gt;
        ///			&lt;DataColumn ColumnName=&quot;strID&quot; DataType=&quot;System.String&quot; Caption=&quot;strID&quot; /&gt;
        ///			&lt;DataColumn ColumnName=&quot;strIDName&quot; DataType=&quot;System.String&quot; Caption=&quot;strIDName&quot; /&gt;
        ///		&lt;/DataColumns&gt;
        ///		&lt;DataRows&gt;
        ///			&lt;DataRow&gt;
        ///				&lt;items ColumnName=&quot;strID&quot;&gt;0 &lt;/items&gt;
        ///				&lt;items ColumnName=&quot;strIDName&quot;&gt;*&lt;/items&gt;
        ///			&lt;/DataRow&gt;
        ///			&lt;DataRow&gt;
        ///				&lt;items ColumnName=&quot;strID&quot;&gt;AY01&lt;/items&gt;
        ///				&lt;items Column [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string IDName {
            get {
                return ResourceManager.GetString("IDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FileName Name=&quot;tblWeight.xml&quot;&gt;
        ///	&lt;DataTable TableName=&quot;tblWeight&quot;&gt;
        ///		&lt;DataColumns&gt;
        ///			&lt;DataColumn ColumnName=&quot;lngSN&quot; DataType=&quot;System.Int32&quot; Caption=&quot;lngSN&quot; /&gt;
        ///			&lt;DataColumn ColumnName=&quot;strInput&quot; DataType=&quot;System.String&quot; Caption=&quot;strInput&quot; /&gt;
        ///			&lt;DataColumn ColumnName=&quot;shtWeight&quot; DataType=&quot;System.Single&quot; Caption=&quot;shtWeight&quot; /&gt;
        ///		&lt;/DataColumns&gt;
        ///		&lt;DataRows&gt;
        ///			&lt;DataRow&gt;
        ///				&lt;items ColumnName=&quot;lngSN&quot;&gt;61&lt;/items&gt;
        ///				&lt;items ColumnName=&quot;strInput&quot;&gt;XX01YY01&lt;/items [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string LifeWeight {
            get {
                return ResourceManager.GetString("LifeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FileName Name=&quot;tblP60Flower.xml&quot;&gt;
        ///  &lt;DataTable TableName=&quot;tblP60Flower&quot;&gt;
        ///    &lt;DataColumns&gt;
        ///      &lt;DataColumn ColumnName=&quot;strXYID&quot; DataType=&quot;System.String&quot; Caption=&quot;strXYID&quot; /&gt;
        ///      &lt;DataColumn ColumnName=&quot;strNFID&quot; DataType=&quot;System.String&quot; Caption=&quot;strNFID&quot; /&gt;
        ///    &lt;/DataColumns&gt;
        ///    &lt;DataRows&gt;
        ///      &lt;DataRow&gt;
        ///        &lt;items ColumnName=&quot;strXYID&quot;&gt;XX01YY01&lt;/items&gt;
        ///        &lt;items ColumnName=&quot;strNFID&quot;&gt;NF01&lt;/items&gt;
        ///      &lt;/DataRow&gt;
        ///      &lt;DataRow&gt;
        ///        &lt;item [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string P60Flower {
            get {
                return ResourceManager.GetString("P60Flower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FileName Name=&quot;tblP60To5Element.xml&quot;&gt;
        ///  &lt;DataTable TableName=&quot;tblP60To5Element&quot;&gt;
        ///    &lt;DataColumns&gt;
        ///      &lt;DataColumn ColumnName=&quot;strNFID&quot; DataType=&quot;System.String&quot; Caption=&quot;strNFID&quot; /&gt;
        ///      &lt;DataColumn ColumnName=&quot;strNEID&quot; DataType=&quot;System.String&quot; Caption=&quot;strNEID&quot; /&gt;
        ///    &lt;/DataColumns&gt;
        ///    &lt;DataRows&gt;
        ///      &lt;DataRow&gt;
        ///        &lt;items ColumnName=&quot;strNFID&quot;&gt;NF01&lt;/items&gt;
        ///        &lt;items ColumnName=&quot;strNEID&quot;&gt;NE04&lt;/items&gt;
        ///      &lt;/DataRow&gt;
        ///      &lt;DataRow&gt;
        ///        &lt; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string P60To5Element {
            get {
                return ResourceManager.GetString("P60To5Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FileName Name=&quot;StarLocation.xml&quot;&gt;
        ///	&lt;DataTable TableName=&quot;tblStarLocation&quot;&gt;
        ///		&lt;DataColumns&gt;
        ///			&lt;DataColumn ColumnName=&quot;strID&quot; DataType=&quot;System.String&quot; Caption=&quot;strID&quot; /&gt;
        ///			&lt;DataColumn ColumnName=&quot;strLocationID&quot; DataType=&quot;System.String&quot; Caption=&quot;strLocationID&quot; /&gt;
        ///		&lt;/DataColumns&gt;
        ///		&lt;DataRows&gt;
        ///			&lt;DataRow&gt;
        ///				&lt;items ColumnName=&quot;strID&quot;&gt;FX07XX09&lt;/items&gt;
        ///				&lt;items ColumnName=&quot;strLocationID&quot;&gt;AY01&lt;/items&gt;
        ///			&lt;/DataRow&gt;
        ///			&lt;DataRow&gt;
        ///				&lt;items ColumnName=&quot;strID [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string StarLocation {
            get {
                return ResourceManager.GetString("StarLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FileName Name=&quot;StarStrongWeak.xml&quot;&gt;
        ///	&lt;DataTable TableName=&quot;tblStarStrongWeak&quot;&gt;
        ///		&lt;DataColumns&gt;
        ///			&lt;DataColumn ColumnName=&quot;strStarYY&quot; DataType=&quot;System.String&quot; Caption=&quot;strStarYY&quot; /&gt;
        ///			&lt;DataColumn ColumnName=&quot;strStarPY&quot; DataType=&quot;System.String&quot; Caption=&quot;strStarPY&quot; /&gt;
        ///		&lt;/DataColumns&gt;
        ///		&lt;DataRows&gt;
        ///			&lt;DataRow&gt;
        ///				&lt;items ColumnName=&quot;strStarYY&quot;&gt;AY01YY02&lt;/items&gt;
        ///				&lt;items ColumnName=&quot;strStarPY&quot;&gt;AY01PY01&lt;/items&gt;
        ///			&lt;/DataRow&gt;
        ///			&lt;DataRow&gt;
        ///				&lt;items ColumnNam [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string StarStrongWeak {
            get {
                return ResourceManager.GetString("StarStrongWeak", resourceCulture);
            }
        }
    }
}
